### ISSUE TITLE
Add info to the documentation about creating Bridging Header for Swift

### ISSUE THREAD

**Issue by lastant** [thevikke/read_pdf_text#4]
I faced multiple linker errors on iOS like:

`Could not find or use auto-linked library 'swiftObjectiveC`

Then found the solution here: https://stackoverflow.com/a/54586937/2881394
I think this should be added to the Installation section of the documentation.

**Comment by thevikke** [comment]
Thank you for the report. I will look into it when I get home.

**Comment by thevikke** [comment]
Sorry I forgot this for awhile. But I updated the README.md to reflect this issue.
