### ISSUE TITLE
Background young concurrent copying GC freed 515270(13MB) AllocSpace objects, 19(4168KB) LOS objects, 34% free, 25MB/39MB, paused 90us total 110.917ms

### ISSUE THREAD

**Issue by SopheaII** [thevikke/read_pdf_text#5]
` A resource failed to call end.`
`Background young concurrent copying GC freed 515270(13MB) AllocSpace objects, 19(4168KB) LOS objects, 34% free, 25MB/39MB, paused 90us total 110.917ms`
May I know what the cause of this probleme?

**Comment by SopheaII** [comment]
For GC, it's my mistake in my code, but for `A resource failed to call end` still happen, but not yet affect any of output.

**Comment by thevikke** [comment]
Yes I am aware of this warning. I think it is from PDFBox package running on Android. Seems to me that it doesn't affect the output.
