### ISSUE TITLE
Application crash android

### ISSUE THREAD

**Issue by Vinayak006** [thevikke/read_pdf_text#9]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.tom_roush:pdfbox-android:1.8.10.1.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/tom_roush/pdfbox-android/1.8.10.1/pdfbox-android-1.8.10.1.pom
       - https://repo.maven.apache.org/maven2/com/tom_roush/pdfbox-android/1.8.10.1/pdfbox-android-1.8.10.1.pom
       - https://storage.googleapis.com/download.flutter.io/com/tom_roush/pdfbox-android/1.8.10.1/pdfbox-android-1.8.10.1.pom
       - https://jcenter.bintray.com/com/tom_roush/pdfbox-android/1.8.10.1/pdfbox-android-1.8.10.1.pom
     Required by:
         project :app > project :read_pdf_text

**Comment by lecanhhiep** [comment]
I have created a temporarily fix for that, if you're still stuck with this, feel free to use this setting in your pubspec.yml 


  read_pdf_text:    #work ios
    git:
      url: https://github.com/lecanhhiep/read_pdf_text.git
      ref: v10

**Comment by thevikke** [comment]
I will check this out next week. Thank you for the information!

**Comment by Vinayak006** [comment]
> I have created a temporarily fix for that, if you're still stuck with this, feel free to use this setting in your pubspec.yml
> 
> ```
> read_pdf_text:
>     git:
>       url: https://github.com/lecanhhiep/read_pdf_text.git
>       ref: v10
> ```

Thanks for the fix! We'll give it a try. :+1:

**Comment by Vinayak006** [comment]
> I will check this out next week. Thank you for the information!

We appreciate you looking into it and we'll keep an eye out for any updates. :+1:

**Comment by thevikke** [comment]
Check version [0.2.2](https://pub.dev/packages/read_pdf_text/versions).
